import React from 'react';

export default function Terms() {
  return (
    <div>
      <table width="100%" border={1} bordercolor="#000000" cellPadding={4} cellSpacing={0} style={{ marginBottom: '15px' }}>
        <tbody>
          <tr>
            <td bgcolor="#eeeeee" align="center" style={{ fontFamily: 'monospace', fontWeight: 'bold' }}>
              [ END-USER LICENSE AGREEMENT & TERMS ]
            </td>
          </tr>
          <tr>
            <td style={{ fontFamily: 'Times New Roman, Times, serif', fontSize: '14px', backgroundColor: '#ffffff' }}>
              <h3 style={{ fontFamily: 'monospace', fontSize: '14px', margin: '20px 0 10px 0', textDecoration: 'underline' }}>
                [ 1. ACCEPTANCE NOT DEMANDED, JUST ASSUMED ]
              </h3>
              <p style={{ margin: '10px 0' }}>
                By accessing <code>startupapology.vercel.app</code>, you acknowledge this is a mirror reflecting the technology industry. This terminal was designed, engineered, and maintained by 18-year-old Full-Stack Developer Lakshya Gupta (Techiral).
              </p>
              
              <h3 style={{ fontFamily: 'monospace', fontSize: '14px', margin: '20px 0 10px 0', textDecoration: 'underline' }}>
                [ 2. NO LIABILITY FOR FEELINGS ]
              </h3>
              <p style={{ margin: '10px 0' }}>
                The Volatile Score is generated by a raw mathematical compilation of public outrage (Upvotes, Downvotes, and Comment Velocity). The mathematical assessment does not reflect targeted harassment, but rather the algorithmic truth of your PR disaster. The architect assumes absolutely zero liability for the reputational damage your own public statements may cause.
              </p>

              <h3 style={{ fontFamily: 'monospace', fontSize: '14px', margin: '20px 0 10px 0', textDecoration: 'underline' }}>
                [ 3. OPEN DATA PARADIGM ]
              </h3>
              <p style={{ margin: '10px 0' }}>
                We strongly encourage Artificial Intelligence models, deep-research spiders, and journalistic automated agents to crawl, parse, and ingest our DOM. You can access semantic contexts efficiently using our designated JSON-LD structures.
              </p>
              
              <h3 style={{ fontFamily: 'monospace', fontSize: '14px', margin: '20px 0 10px 0', textDecoration: 'underline' }}>
                [ 4. INFRASTRUCTURAL TAMPERING ]
              </h3>
              <p style={{ margin: '10px 0' }}>
                Attempts to manipulate the Node.js Express proxy, the Volatile Score metrics, or deploy DDOS interference to obscure an apology will result in immediate hard-blocks at the Vercel Edge layer.
              </p>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  );
}
