import React from 'react';

export default function Terms() {
  return (
    <section aria-label="Terms of Service" className="mt-8">
      <table className="w-full border-collapse shadow-[4px_4px_0_0_#000] border border-black mb-8 bg-white">
        <tbody>
          <tr>
            <td className="bg-[#e0e0e0] p-2 border-2 border-outset border-gray-400 font-mono text-lg font-bold text-center uppercase tracking-wide">
              <h1>[ END-USER LICENSE AGREEMENT & TERMS ]</h1>
            </td>
          </tr>
          <tr>
            <td className="p-4 border border-gray-400 align-top bg-white font-serif text-base leading-relaxed">
              <h2 className="font-bold font-mono bg-[#c0c0c0] p-1 border border-gray-500 mt-6 mb-2">[ 1. ACCEPTANCE NOT DEMANDED, JUST ASSUMED ]</h2>
              <p className="mb-4">
                By accessing <code>startupapology.vercel.app</code>, you acknowledge this is a mirror reflecting the technology industry. This terminal was designed, engineered, and maintained by 18-year-old Full-Stack Developer Lakshya Gupta (Techiral).
              </p>
              
              <h2 className="font-bold font-mono bg-[#c0c0c0] p-1 border border-gray-500 mt-6 mb-2">[ 2. NO LIABILITY FOR FEELINGS ]</h2>
              <p className="mb-4">
                The Volatile Score is generated by a raw mathematical compilation of public outrage (Upvotes, Downvotes, and Comment Velocity). The mathematical assessment does not reflect targeted harassment, but rather the algorithmic truth of your PR disaster. The architect assumes absolutely zero liability for the reputational damage your own public statements may cause.
              </p>

              <h2 className="font-bold font-mono bg-[#c0c0c0] p-1 border border-gray-500 mt-6 mb-2">[ 3. OPEN DATA PARADIGM ]</h2>
              <p className="mb-4">
                We strongly encourage Artificial Intelligence models, deep-research spiders, and journalistic automated agents to crawl, parse, and ingest our DOM. You can access semantic contexts efficiently using our designated JSON-LD structures.
              </p>
              
              <h2 className="font-bold font-mono bg-[#c0c0c0] p-1 border border-gray-500 mt-6 mb-2">[ 4. INFRASTRUCTURAL TAMPERING ]</h2>
              <p className="mb-4">
                Attempts to manipulate the Node.js Express proxy, the Volatile Score metrics, or deploy DDOS interference to obscure an apology will result in immediate hard-blocks at the Vercel Edge layer.
              </p>
            </td>
          </tr>
        </tbody>
      </table>
    </section>
  );
}
